/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;
import bussiness.Employee;
import javax.swing.JOptionPane;
import data.Employeedb;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.io.*;



/**
 *
 * @author rheem
 */
public class EmployeeUI extends javax.swing.JFrame {
   private Employeedb EDB;
   // private Employeedb EDB1;
    private DefaultTableModel tblModel;
   

    /**
     * Creates new form EmployeeUI
     */
    public EmployeeUI() {
       initComponents();
        setLocationRelativeTo(this);
        EDB=new Employeedb();
      //EDB1=new Employeedb(); 
        tblModel=new DefaultTableModel();
       tblemp.setModel(tblModel);
       tblModel.addColumn("Employee id");
        tblModel.addColumn("Emp name");
         tblModel.addColumn("EPF no");
         tblModel.addColumn("Contact number");
         tblModel.addColumn("Department");
         tblModel.addColumn("Designation");
        
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        popupMenu1 = new java.awt.PopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblemployee = new javax.swing.JTable();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        popupMenu2 = new java.awt.PopupMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuBar9 = new javax.swing.JMenuBar();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuBar10 = new javax.swing.JMenuBar();
        jMenu20 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenuBar11 = new javax.swing.JMenuBar();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenuBar12 = new javax.swing.JMenuBar();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblEmpID = new javax.swing.JLabel();
        lblEmpname = new javax.swing.JLabel();
        lblEPFnumber = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblDesignation = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        txtEmpName = new javax.swing.JTextField();
        txtEpfno = new javax.swing.JTextField();
        cmbDep = new javax.swing.JComboBox<>();
        cmbDesignation = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rdoReset = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        lblcontact = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        btnDisplayAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblemp = new javax.swing.JTable();
        btncancel1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnufile = new javax.swing.JMenu();
        mnuMainMenuUI = new javax.swing.JMenuItem();
        MnuCancel = new javax.swing.JMenuItem();
        mnuRecords = new javax.swing.JMenu();
        mnusearch = new javax.swing.JMenuItem();
        mnuDelete = new javax.swing.JMenuItem();
        mnuUpdate = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenuItem4.setText("jMenuItem4");

        jMenu5.setText("jMenu5");

        jMenuItem5.setText("jMenuItem5");

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar5.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar5.add(jMenu9);

        jMenuItem6.setText("jMenuItem6");

        jMenu10.setText("File");
        jMenuBar6.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar6.add(jMenu11);

        jMenu12.setText("File");
        jMenuBar7.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar7.add(jMenu13);

        jMenu14.setText("File");
        jMenuBar8.add(jMenu14);

        jMenu15.setText("Edit");
        jMenuBar8.add(jMenu15);

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        tblemployee.setBackground(new java.awt.Color(255, 255, 51));
        tblemployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 102), 1, true));
        tblemployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblemployee);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu2.setLabel("popupMenu2");

        jMenuItem9.setText("jMenuItem9");

        jMenu17.setText("jMenu17");

        jMenu18.setText("File");
        jMenuBar9.add(jMenu18);

        jMenu19.setText("Edit");
        jMenuBar9.add(jMenu19);

        jMenu20.setText("File");
        jMenuBar10.add(jMenu20);

        jMenu21.setText("Edit");
        jMenuBar10.add(jMenu21);

        jMenu22.setText("File");
        jMenuBar11.add(jMenu22);

        jMenu23.setText("Edit");
        jMenuBar11.add(jMenu23);

        jMenu24.setText("File");
        jMenuBar12.add(jMenu24);

        jMenu25.setText("Edit");
        jMenuBar12.add(jMenu25);

        jMenu26.setText("jMenu26");

        setTitle("Add Employee detail");
        setBackground(new java.awt.Color(0, 153, 153));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        lblEmpID.setText("Employee ID");

        lblEmpname.setText("Employee Name");

        lblEPFnumber.setText("Emp EPF No");

        lblDepartment.setText("Department");

        lblDesignation.setText("Designation");

        txtEmpID.setToolTipText(" 4 digit number");
        txtEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpIDActionPerformed(evt);
            }
        });

        txtEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNameActionPerformed(evt);
            }
        });

        cmbDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administration ", "Academic", "Coordinators", "Financial ", "HR ", "Marketting", " " }));

        cmbDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accountant", "Admin", "Finance", "HR ", "Leacturer", "Marketting ", "Coordinator", " " }));
        cmbDesignation.setToolTipText("");
        cmbDesignation.setComponentPopupMenu(jPopupMenu1);
        cmbDesignation.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDesignationActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 0, 153));
        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 255));
        jLabel1.setText("Employee Detail");
        jLabel1.setToolTipText("Add relevent employee detail to relevent fields");

        rdoReset.setText("Reset");
        rdoReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoResetActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        lblcontact.setText("Contact  Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rdoReset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btncancel)
                        .addGap(95, 95, 95)
                        .addComponent(btnAdd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(cmbDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEPFnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpname, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEmpName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(txtEpfno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcontact)
                                    .addComponent(txtEmpID)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDep, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpID)
                    .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpname)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEPFnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEpfno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontact)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartment))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesignation)
                    .addComponent(cmbDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(rdoReset)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btncancel))
                .addGap(86, 86, 86))
        );

        panel1.setBackground(new java.awt.Color(0, 153, 153));

        btnDisplayAll.setText("Display All");
        btnDisplayAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayAllActionPerformed(evt);
            }
        });

        tblemp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(255, 204, 204), null, null));
        tblemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee id", "Employee Name", "EPF number", "Department", "Designation", "Contact number"
            }
        ));
        tblemp.setAutoscrolls(false);
        tblemp.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        tblemp.setGridColor(new java.awt.Color(153, 204, 0));
        tblemp.setRowHeight(40);
        tblemp.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblemp.setSelectionForeground(new java.awt.Color(0, 153, 153));
        tblemp.setShowGrid(true);
        jScrollPane1.setViewportView(tblemp);
        tblemp.getAccessibleContext().setAccessibleParent(lblDesignation);

        btncancel1.setBackground(new java.awt.Color(0, 153, 153));
        btncancel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 14)); // NOI18N
        btncancel1.setForeground(new java.awt.Color(255, 51, 51));
        btncancel1.setText("X");
        btncancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btncancel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnDisplayAll)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncancel1)
                .addGap(2, 2, 2)
                .addComponent(btnDisplayAll)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mnufile.setText("File");

        mnuMainMenuUI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuMainMenuUI.setText("Main Menu");
        mnuMainMenuUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMainMenuUIActionPerformed(evt);
            }
        });
        mnufile.add(mnuMainMenuUI);

        MnuCancel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MnuCancel.setText("Exit");
        MnuCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCancelActionPerformed(evt);
            }
        });
        mnufile.add(MnuCancel);

        jMenuBar1.add(mnufile);

        mnuRecords.setText("Records");
        mnuRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRecordsActionPerformed(evt);
            }
        });

        mnusearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnusearch.setText("Search Records");
        mnusearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnusearchActionPerformed(evt);
            }
        });
        mnuRecords.add(mnusearch);

        mnuDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuDelete.setText("Delete Record");
        mnuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteActionPerformed(evt);
            }
        });
        mnuRecords.add(mnuDelete);

        mnuUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuUpdate.setText("Update Record");
        mnuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUpdateActionPerformed(evt);
            }
        });
        mnuRecords.add(mnuUpdate);

        jMenuBar1.add(mnuRecords);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpIDActionPerformed

    private void cmbDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDesignationActionPerformed

    private void mnuMainMenuUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMainMenuUIActionPerformed
        // TODO add your handling code here:
        MainMenuUI MUI=new MainMenuUI();
        MUI.setVisible(true);
        
    }//GEN-LAST:event_mnuMainMenuUIActionPerformed

    private void MnuCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_MnuCancelActionPerformed

    private void txtEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNameActionPerformed

    private void mnuRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRecordsActionPerformed
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_mnuRecordsActionPerformed

    private void mnusearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnusearchActionPerformed
        // TODO add your handling code here:
   
        EmployeeUI EMPUI=new EmployeeUI();
         
        int EmployeeID=Integer.valueOf(JOptionPane.showInputDialog("Enter Employee ID"));
        Employee E=EDB.search(EmployeeID);
        if(E!=null){
            
          EMPUI.txtEmpID.setText(String.valueOf(E.getEmpID()));
         EMPUI.txtEmpName.setText(E.getEmpName());
         EMPUI.txtEpfno.setText(String.valueOf(E.getEPFnumber()));
           EMPUI.txtcontact.setText(String.valueOf(E.getContact()));
         EMPUI.cmbDep.setSelectedItem(E.getDepartment());
         EMPUI.cmbDesignation.setSelectedItem(E.getDesignation());
         // EMPUI.txtEmpID.setText(String.valueOf(E.getEmpID()));
          EMPUI.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane, "This record not found");
           //txtEmpID.setText(String.valueOf(E)E.getEmpID());
            //txtEmpName.setText(E.getEmpName());
        
        } 
     
   
        
    }//GEN-LAST:event_mnusearchActionPerformed

    private void mnuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteActionPerformed
        // TODO add your handling code here:
         int EmployeeID=Integer.valueOf(JOptionPane.showInputDialog("Enter Employee ID"));
        boolean deleted=EDB.delete(EmployeeID);
        if(deleted){
            JOptionPane.showMessageDialog(rootPane, "Record sucessfully deleted");
            
        }else{
             JOptionPane.showMessageDialog(rootPane, "Record not deleted");
            
            
        }
    }//GEN-LAST:event_mnuDeleteActionPerformed

    private void mnuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUpdateActionPerformed
        // TODO add your handling code here:  
         if (checkValidation()){
        
        int EmpID=Integer.valueOf(txtEmpID.getText());
        String EmpName=txtEmpName.getText();
        String EPFnumber=txtEpfno.getText();
        int contact=Integer.valueOf(txtcontact.getText());
        String Department=String.valueOf(cmbDep.getSelectedItem());
        String Designation =String.valueOf(cmbDesignation.getSelectedItem());
      Employee E=new Employee(EmpID,EmpName,EPFnumber,contact,Department,Designation);
      
      boolean result=EDB.update(E);
     if (result){
         JOptionPane.showMessageDialog(this,"New Employee successfully updated");
       //  JOptionPane.showMessageDialog(this,EDB);
     }else{
         JOptionPane.showMessageDialog(this,"Employee not updated");
         
  
     }
    }//GEN-LAST:event_mnuUpdateActionPerformed
    
    }
    private void rdoResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoResetActionPerformed
        // TODO add your handling code here:
        txtEmpID.setText("");
        txtEmpName.setText("");
        txtEpfno.setText("");
        txtcontact.setText("");
        cmbDep.setSelectedItem(0);
        cmbDesignation.setSelectedItem(0);
    }//GEN-LAST:event_rdoResetActionPerformed

    private void btnDisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayAllActionPerformed
        // TODO add your handling code here:
         ArrayList<Employee> EList=EDB.getAll();
        tblModel.setRowCount(0);
        for(Employee E:EList){
            int EmpID=E.getEmpID();
            String EmpName=E.getEmpName();
            String EPFnumber=E.getEPFnumber();
            int contact=E.getContact();
            String Department=E.getDepartment();
            String Designation=E.getDesignation();
            //Empnumber

            tblModel.addRow(new Object[]{EmpID,EmpName,EPFnumber,contact,Department,Designation});
    }//GEN-LAST:event_btnDisplayAllActionPerformed
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         if (checkValidation()){
        
        int EmpID=Integer.valueOf(txtEmpID.getText());
        String EmpName=txtEmpName.getText();
        String EPFnumber=txtEpfno.getText();
        int contact=Integer.valueOf(txtcontact.getText());
        String Department=String.valueOf(cmbDep.getSelectedItem());
        String Designation =String.valueOf(cmbDesignation.getSelectedItem());
      Employee E=new Employee(EmpID,EmpName,EPFnumber,contact,Department,Designation);
      
            tblModel.addRow(new Object[]{EmpID,EmpName,EPFnumber,contact,Department,Designation});
      
      boolean result=EDB.add(E);
     if (result){
         JOptionPane.showMessageDialog(this,"New Employee successfully added");
       //  JOptionPane.showMessageDialog(this,EDB);
     }else{
         JOptionPane.showMessageDialog(this,"Employee not added");
         
     }
         }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
         setVisible(false);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btncancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel1ActionPerformed
        // TODO add your handling code here:
          setVisible(false);
    }//GEN-LAST:event_btncancel1ActionPerformed
    
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeUI().setVisible(true);
            }
        });
    }
       private boolean checkValidation(){
     
          
          if(txtEmpID.getText().equals("")){
              JOptionPane.showMessageDialog(this,"Employee id cannot be blank");
              return false;
          }
          try{
               int EmpID=Integer.valueOf(txtEmpID.getText());
          }catch(Exception e){
          JOptionPane.showMessageDialog(this,"Employee id must be numeric");
          return false;
           }


                  
          
             if(txtEmpName.getText().equals("")){
              JOptionPane.showMessageDialog(this,"Employee name cannot be blank");
              return false;
             }
                if(txtEpfno.getText().equals("")){
              JOptionPane.showMessageDialog(this,"Employee EPF number cannot be blank");
              return false;
                }
                 
                return true;
       }
       
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuCancel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDisplayAll;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncancel1;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cmbDep;
    public javax.swing.JComboBox<String> cmbDesignation;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar10;
    private javax.swing.JMenuBar jMenuBar11;
    private javax.swing.JMenuBar jMenuBar12;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDesignation;
    private javax.swing.JLabel lblEPFnumber;
    public javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblEmpname;
    private javax.swing.JLabel lblcontact;
    private javax.swing.JMenuItem mnuDelete;
    private javax.swing.JMenuItem mnuMainMenuUI;
    private javax.swing.JMenu mnuRecords;
    private javax.swing.JMenuItem mnuUpdate;
    private javax.swing.JMenu mnufile;
    private javax.swing.JMenuItem mnusearch;
    private java.awt.Panel panel1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JRadioButton rdoReset;
    private javax.swing.JTable tblemp;
    private javax.swing.JTable tblemployee;
    public javax.swing.JTextField txtEmpID;
    public javax.swing.JTextField txtEmpName;
    public javax.swing.JTextField txtEpfno;
    private javax.swing.JTextField txtcontact;
    // End of variables declaration//GEN-END:variables
}
